language: java
jdk:
  - oraclejdk8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo No X11
  - sleep 3
script:
  - java -version
  - mvn install -DskipTests
  - mvn test
os:
  - linux
  - osx
